-- Inizializzazione della scuola

CREATE TABLE IF NOT EXISTS scuola (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    nome            text NOT NULL,
    codice_fiscale  text NOT NULL
);

INSERT INTO scuola (nome, codice_fiscale)
SELECT 'Danza con noi A.S.D.', '24258481308'
WHERE NOT EXISTS (
    SELECT 1
    FROM scuola
    WHERE nome = 'Danza con noi A.S.D.'
      AND codice_fiscale = '24258481308'
);
