-- Ballroom PostgreSQL schema

CREATE TABLE IF NOT EXISTS scuola (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    nome            text NOT NULL,
    codice_fiscale  text NOT NULL
);

CREATE TABLE IF NOT EXISTS sala (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted     boolean NOT NULL DEFAULT false,
    nome        text NOT NULL
);

CREATE TABLE IF NOT EXISTS utente (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    nome            text NOT NULL UNIQUE,
    password        text NOT NULL,
    temp_password   text NOT NULL,
    scad_password   timestamptz,
    tipo_ruolo      smallint NOT NULL CHECK (tipo_ruolo BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS crew (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted     boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS persona (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    tipo_persona    smallint NOT NULL CHECK (tipo_persona BETWEEN 1 AND 3),
    nome            text NOT NULL,
    cognome         text NOT NULL,
    data_nascita    timestamptz,
    codice_fiscale  text NOT NULL DEFAULT '',
    id_crew         integer REFERENCES crew(id) DEFERRABLE INITIALLY DEFERRED,
    id_utente       integer REFERENCES utente(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS crew_allievo (
    id_crew     integer NOT NULL REFERENCES crew(id) ON DELETE CASCADE,
    id_allievo  integer NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    PRIMARY KEY (id_crew, id_allievo)
);

CREATE TABLE IF NOT EXISTS contatto (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted     boolean NOT NULL DEFAULT false,
    tipo        smallint NOT NULL CHECK (tipo BETWEEN 1 AND 2),
    valore      text NOT NULL,
    id_owner    integer NOT NULL,
    preferito   boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX IF NOT EXISTS contatto_preferito_owner_idx
    ON contatto (id_owner)
    WHERE preferito AND NOT deleted;

CREATE TABLE IF NOT EXISTS certificazione (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    deleted                 boolean NOT NULL DEFAULT false,
    certificato_agonistico  boolean NOT NULL DEFAULT false,
    data_rilascio          timestamptz,
    data_scadenza          timestamptz,
    medico                  text NOT NULL DEFAULT '',
    protocollo              text NOT NULL DEFAULT '',
    id_allievo              integer NOT NULL REFERENCES persona(id)
);

CREATE TABLE IF NOT EXISTS affiliazione (
    id                              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                      timestamptz NOT NULL DEFAULT now(),
    updated_at                      timestamptz NOT NULL DEFAULT now(),
    deleted                         boolean NOT NULL DEFAULT false,
    codice                          text NOT NULL,
    nome                            text NOT NULL,
    data_prima_iscrizione           timestamptz,
    data_scadenza_iscrizione_ac     timestamptz,
    data_inizio_as                  timestamptz,
    data_fine_as                    timestamptz
);

CREATE TABLE IF NOT EXISTS tesseramento (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),
    deleted                     boolean NOT NULL DEFAULT false,
    id_tesserato                integer NOT NULL REFERENCES persona(id),
    id_affiliazione             integer NOT NULL REFERENCES affiliazione(id),
    tesserato_agonistico        boolean NOT NULL DEFAULT false,
    nro_tessera                 text NOT NULL DEFAULT '',
    data_primo_tesseramento     timestamptz,
    data_scadenza_tessera_ac    timestamptz,
    UNIQUE (id_tesserato, id_affiliazione)
);

CREATE TABLE IF NOT EXISTS corso (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    tipo            smallint NOT NULL CHECK (tipo BETWEEN 1 AND 3),
    titolo          text NOT NULL,
    id_sala         integer REFERENCES sala(id) ON DELETE SET NULL,
    data_inizio     timestamptz,
    data_fine       timestamptz
);

CREATE TABLE IF NOT EXISTS orario (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_corso    integer NOT NULL REFERENCES corso(id) ON DELETE CASCADE,
    giorno      smallint NOT NULL CHECK (giorno BETWEEN 1 AND 7),
    ora_inizio  timestamptz,
    ora_fine    timestamptz,
    UNIQUE (id_corso, giorno, ora_inizio)
);

CREATE TABLE IF NOT EXISTS programmazione (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    id_corso        integer NOT NULL REFERENCES corso(id) ON DELETE CASCADE,
    id_allievo      integer NOT NULL REFERENCES persona(id),
    id_insegnante   integer NOT NULL REFERENCES persona(id),
    UNIQUE (id_corso, id_allievo, id_insegnante)
);

CREATE TABLE IF NOT EXISTS gara (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted     boolean NOT NULL DEFAULT false,
    tipo        smallint NOT NULL CHECK (tipo BETWEEN 1 AND 3),
    titolo      text NOT NULL,
    id_sala     integer REFERENCES sala(id) ON DELETE SET NULL,
    data_inizio timestamptz,
    data_fine   timestamptz
);

CREATE TABLE IF NOT EXISTS iscrizione (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted     boolean NOT NULL DEFAULT false,
    id_gara     integer NOT NULL REFERENCES gara(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS iscrizione_allievo (
    id_iscrizione  integer NOT NULL REFERENCES iscrizione(id) ON DELETE CASCADE,
    id_allievo     integer NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    PRIMARY KEY (id_iscrizione, id_allievo)
);